# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "better-free-shipping"
client_id = "6ac6fc9b7d3a8a65f4cde5fa47a99ef0"
application_url = "https://million-is-ghost-keys.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://million-is-ghost-keys.trycloudflare.com/auth/callback",
  "https://million-is-ghost-keys.trycloudflare.com/auth/shopify/callback",
  "https://million-is-ghost-keys.trycloudflare.com/api/auth/callback",
  "https://million-is-ghost-keys.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "appmixo-bhavin.myshopify.com"
